### PR TITLE
Test Template fix

### PR DESCRIPTION
**Pull request by malkaviano**
- Fixed missing imports;
- Changed get route from derp to model name;
- removed unused imports;

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @malkaviano,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by renatocaval** [comment]
CLA is signed: https://www.lightbend.com/contribute/cla/check/malkaviano

**Comment by octonato** [comment]
This PR was originally sent to 2.6.x, but default branch is now 2.7.x. 

We should cherrypick it on 2.7.x once merged.

**Comment by marcospereira** [comment]
Closing and reopening to trigger a new build.

**Review by marcospereira — APPROVED** [review]

**Comment by ignasi35** [comment]
forward port `2.7.x` 96162f953cf9c8f60a5e5d910314a651a5c2fbc1

**Pull request merged**
